import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";
import { Inconsolata } from "next/font/google";
import QueryProvider from "@/components/ui/queryclient-provider";

const inter = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
